### ISSUE TITLE
SNI fails after upgrade - SSL_ERROR_BAD_CERT_DOMAIN

### ISSUE THREAD

**Issue by andrewwebber** [zlabjp/nghttpx-ingress-lb#36] opened 2017-03-08 17:21 UTC
When using multiple ingress rules with different certificates only one certificates is dominant.
Example:
-ingress rule 1: foo.bar.com using certificate *.bar.com
-ingress rule 2: bar.foo.com using certificate *.foo.com

```bash
curl bar.foo.com
```
Client fails with SSL_ERROR_BAD_CERT_DOMAIN and receives certificate for *.bar.com
```bash
curl -kv bar.foo.com 
```
Client receives traffic ignoring certificate validation

This works on 0.18 but the same rules fail on 0.19
Is this a SNI processing issue?

**Comment by andrewwebber** [comment] 2017-03-08 17:41
Below are the generated configuration files from version 0.18 and 0.19
```bash
root@localhost:/# cat /etc/nghttpx/nghttpx.conf 18

accesslog-file=/dev/stdout

include=/etc/nghttpx/nghttpx-backend.conf

frontend=*,80;no-tls

# API endpoints
frontend=127.0.0.1,3001;api;no-tls


frontend=*,443


# checksum is required to detect changes in the generated configuration and force a reload
# checksum: 6d06cd15764433cfb7157f3cb6d571aee57455b684404c6d507bdecc7b07c457
private-key-file=/etc/nghttpx-tls/brainloop_ingress-brainloop-cert.key
certificate-file=/etc/nghttpx-tls/brainloop_ingress-brainloop-cert.crt


# checksum: 0aab568950229dae8e20870641cf276b83894bf9b6c5a5935015f962aa16890e
subcert=/etc/nghttpx-tls/brainloop_ingress-cert.key:/etc/nghttpx-tls/brainloop_ingress-cert.crt

# checksum: 0aab568950229dae8e20870641cf276b83894bf9b6c5a5935015f962aa16890e
subcert=/etc/nghttpx-tls/kube-system_dashboard-ingress-cert.key:/etc/nghttpx-tls/kube-system_dashboard-ingress-cert.crt

# checksum: 31884b4a0f60d544c440750efdbf6700a1a13bc8555cfb90ba9bde3d40a4465f
subcert=/etc/nghttpx-tls/rhino-ci_gateway-external-cert.key:/etc/nghttpx-tls/rhino-ci_gateway-external-cert.crt

# checksum: ff2b53055f68aba15c9c5a39a48393ff228185a8c5f4760ddb469ed8bd13366f
subcert=/etc/nghttpx-tls/rhino-ci_ingress-thirdparty-cert.key:/etc/nghttpx-tls/rhino-ci_ingress-thirdparty-cert.crt




# for health check
frontend=127.0.0.1,8080;healthmon;no-tls

# default configuration by controller
workers=2

# from ConfigMap

insecure=yes
server-name=brainloop
no-via=yes

root@localhost:/# cat /etc/nghttpx/nghttpx-backend.conf 
# brainloop/dox-build-mon-service,3000;build-mon.brainloopdevops.com/
backend=11.2.79.4,3000;build-mon.brainloopdevops.com/;proto=http/1.1;affinity=none
# brainloop/dox-platforms-service,3000;platforms.brainloopdevops.com/
backend=11.2.60.4,3000;platforms.brainloopdevops.com/;proto=http/1.1;affinity=none
# brainloop/dox-wiki-service,80;wiki.brainloopdevops.com/
backend=11.2.14.6,80;wiki.brainloopdevops.com/;proto=http/1.1;affinity=none
# brainloop/registry,5000;registry.brainloop.local/
backend=11.2.58.3,5000;registry.brainloop.local/;proto=http/1.1;affinity=none
# brainloop/registry-dashboard,80;registry.brainloopdevops.com/
backend=11.2.58.4,80;registry.brainloopdevops.com/;proto=http/1.1;affinity=none
# brainloop/support,80;support.brainloopdevops.com/
backend=11.2.79.7,80;support.brainloopdevops.com/;proto=http/1.1;affinity=none
# default/default-http-backend
backend=11.2.14.3,8080;;proto=http/1.1;affinity=none
# kube-system/kubernetes-dashboard,80;k8.brainloopdevops.com/
backend=11.2.10.2,9090;k8.brainloopdevops.com/;proto=http/1.1;affinity=none
# rhino-ci/gateway,443;dox.thirdparty.com/
backend=11.2.60.8,443;dox.thirdparty.com/;proto=h2;tls;dns;affinity=none
# rhino-ci/gateway,443;rhino-ci.brainloop.com/
backend=11.2.60.8,443;rhino-ci.brainloop.com/;proto=h2;tls;dns;affinity=none
# rhino-ci/pe,8040;dox.thirdparty.com/pe/
backend=11.2.14.9,8040;dox.thirdparty.com/pe/;proto=h2;tls;dns;affinity=none
# rhino-ci/pe,8040;rhino-ci.brainloop.com/pe/
backend=11.2.14.9,8040;rhino-ci.brainloop.com/pe/;proto=h2;tls;dns;affinity=none
# rhino-ci/push,8013;dox.thirdparty.com/push/
backend=11.2.14.10,8013;dox.thirdparty.com/push/;proto=http/1.1;tls;dns;affinity=none
# rhino-ci/push,8013;rhino-ci.brainloop.com/push/
backend=11.2.14.10,8013;rhino-ci.brainloop.com/push/;proto=http/1.1;tls;dns;affinity=none
```

0.19
```bash
root@localhost:/# cat /etc/nghttpx/nghttpx.conf 19

accesslog-file=/dev/stdout

include=/etc/nghttpx/nghttpx-backend.conf

frontend=*,80;no-tls

# API endpoints
frontend=127.0.0.1,3001;api;no-tls


frontend=*,443


# checksum is required to detect changes in the generated configuration and force a reload
# checksum: e0036e880d9f20b72d6e91d5c61b35d9121149029c4c711b87d9332a4c44da7e 6e2c63ecde79168954f65d2ee05faff7a63f695a4cafb4ba5a5832e31b9ceea8
private-key-file=/etc/nghttpx-tls/brainloop_ingress-brainloop-cert.key
certificate-file=/etc/nghttpx-tls/brainloop_ingress-brainloop-cert.crt


# checksum: 4be0530f852c3288e47bea5d67c89db087899160ee5a39c2e5e8a544b5c32eb3 28f0ea725239151527fafe8223e5cf13589c42fac7e54bf5c171bbd16ebdf2c7
subcert=/etc/nghttpx-tls/brainloop_ingress-cert.key:/etc/nghttpx-tls/brainloop_ingress-cert.crt

# checksum: 4be0530f852c3288e47bea5d67c89db087899160ee5a39c2e5e8a544b5c32eb3 28f0ea725239151527fafe8223e5cf13589c42fac7e54bf5c171bbd16ebdf2c7
subcert=/etc/nghttpx-tls/kube-system_dashboard-ingress-cert.key:/etc/nghttpx-tls/kube-system_dashboard-ingress-cert.crt

# checksum: 97fc243814f7d8944b1dde29810be60d40303552e7b38ad544e043e93e8c4367 acf790c36440132bc7552a3c3efab29bfdc48db7dfe45fad4ba2a4db1de40e54
subcert=/etc/nghttpx-tls/rhino-ci_gateway-external-cert.key:/etc/nghttpx-tls/rhino-ci_gateway-external-cert.crt

# checksum: aabe8a51ed784f4e86b04c10df241cbdc89bd778862b9b939ba39a81d9a80c0c 402309b7507baba282fcc2e2d92cf6dba30aecf3407e02fade9a9b2d57b75d13
subcert=/etc/nghttpx-tls/rhino-ci_ingress-thirdparty-cert.key:/etc/nghttpx-tls/rhino-ci_ingress-thirdparty-cert.crt




# for health check
frontend=127.0.0.1,8080;healthmon;no-tls

# default configuration by controller
workers=2

# from ConfigMap

insecure=yes
server-name=brainloop
no-via=yes

root@localhost:/# cat /etc/nghttpx/nghttpx-backend.conf 
# brainloop/dox-build-mon-service,3000;build-mon.brainloopdevops.com/
backend=11.2.79.4,3000;build-mon.brainloopdevops.com/;proto=http/1.1;affinity=none
# brainloop/dox-platforms-service,3000;platforms.brainloopdevops.com/
backend=11.2.60.4,3000;platforms.brainloopdevops.com/;proto=http/1.1;affinity=none;redirect-if-not-tls
# brainloop/dox-wiki-service,80;wiki.brainloopdevops.com/
backend=11.2.14.6,80;wiki.brainloopdevops.com/;proto=http/1.1;affinity=none
# brainloop/registry,5000;registry.brainloop.local/
backend=11.2.58.3,5000;registry.brainloop.local/;proto=http/1.1;affinity=none;redirect-if-not-tls
# brainloop/registry-dashboard,80;registry.brainloopdevops.com/
backend=11.2.58.4,80;registry.brainloopdevops.com/;proto=http/1.1;affinity=none;redirect-if-not-tls
# brainloop/support,80;support.brainloopdevops.com/
backend=11.2.79.7,80;support.brainloopdevops.com/;proto=http/1.1;affinity=none;redirect-if-not-tls
# default/default-http-backend
backend=11.2.14.3,8080;;proto=http/1.1;affinity=none
# kube-system/kubernetes-dashboard,80;k8.brainloopdevops.com/
backend=11.2.10.2,9090;k8.brainloopdevops.com/;proto=http/1.1;affinity=none;redirect-if-not-tls
# rhino-ci/gateway,443;dox.thirdparty.com/
backend=11.2.60.8,443;dox.thirdparty.com/;proto=h2;tls;dns;affinity=none;redirect-if-not-tls
# rhino-ci/gateway,443;rhino-ci.brainloop.com/
backend=11.2.60.8,443;rhino-ci.brainloop.com/;proto=h2;tls;dns;affinity=none;redirect-if-not-tls
# rhino-ci/pe,8040;dox.thirdparty.com/pe/
backend=11.2.14.9,8040;dox.thirdparty.com/pe/;proto=h2;tls;dns;affinity=none;redirect-if-not-tls
# rhino-ci/pe,8040;rhino-ci.brainloop.com/pe/
backend=11.2.14.9,8040;rhino-ci.brainloop.com/pe/;proto=h2;tls;dns;affinity=none;redirect-if-not-tls
# rhino-ci/push,8013;dox.thirdparty.com/push/
backend=11.2.14.10,8013;dox.thirdparty.com/push/;proto=http/1.1;tls;dns;affinity=none;redirect-if-not-tls
# rhino-ci/push,8013;rhino-ci.brainloop.com/push/
backend=11.2.14.10,8013;rhino-ci.brainloop.com/push/;proto=http/1.1;tls;dns;affinity=none;redirect-if-not-tls

```

**Comment by tatsuhiro-t** [comment] 2017-03-09 05:00
I could not reproduce this.
I made 2 ingress resources:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend1
  annotations:
    kubernetes.io/ingress.class: "nghttpx"
spec:
  tls:
  - secretName: backend1
  rules:
  - host: bar.foo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: backend1
          servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend2
  annotations:
    kubernetes.io/ingress.class: "nghttpx"
spec:
  tls:
  - secretName: backend2
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: backend2
          servicePort: 8080
```

Secret backend1 contains TLS certificate for *.foo.com
Secret backend2 contains TLS certificate for *.bar.com

And then run openssl s_client:

```
$ openssl s_client -connect <IP>:443 -servername bar.foo.com
...
subject=/C=.../CN=*.foo.com
```

```
$ openssl s_client -connect <IP>:443 -servername foo.bar.com
...
subject=/C=.../CN=*.bar.com
```

nghttpx.conf is as follows:

```
accesslog-file=/dev/stdout

include=/etc/nghttpx/nghttpx-backend.conf

frontend=*,80;no-tls

# API endpoints
frontend=127.0.0.1,3001;api;no-tls


frontend=*,443


# checksum is required to detect changes in the generated configuration and force a reload
# checksum: 67987df73308ccae439c7a76d4ccbcaef5076a24ebc7fa471223d2f20e96f3d4 d7b06e5522291ac238e446949e338e6c3e648b853a24a759d8f1e958dc68b0b0
private-key-file=/etc/nghttpx-tls/default_backend1.key
certificate-file=/etc/nghttpx-tls/default_backend1.crt


# checksum: bf205138f729f9c2a8ff24f146cd5a7f4f9209df23af249dce5522a3b6346af8 839b167a182420c6bd875933ed13ae265f5e6c38460e87c327c571d6e859aeca
subcert=/etc/nghttpx-tls/default_backend2.key:/etc/nghttpx-tls/default_backend2.crt




# for health check
frontend=127.0.0.1,8080;healthmon;no-tls

# default configuration by controller
workers=1

# from ConfigMap
```

**Comment by tatsuhiro-t** [comment] 2017-03-13 07:53
@andrewwebber Could you share the minimum set of Ingresses to reproduce this issue, perhaps, using the Ingresses in my previous comment?

**Comment by tatsuhiro-t** [comment] 2017-05-21 09:07
It looks like the regression causes this issue.  I committed the fix into master.  Next release will have the fix.

**Comment by andrewwebber** [comment] 2017-05-23 11:48
@tatsuhiro-t how did you discover this regression and were you able to also reproduce it

**Comment by tatsuhiro-t** [comment] 2017-05-24 00:54
I'm not sure the exact same issue, but the regression I found is that the bug causes nghttpx to select certificate which has wrong SAN.  The exact fix commit is https://github.com/nghttp2/nghttp2/commit/9c1876f542a9d26dbc3d96c36deff60a48d3e239.
I found this bug while I setup nghttp2.org with both RSA and ECDSA certificates.

**Comment by tatsuhiro-t** [comment] 2017-05-29 07:21
@andrewwebber Could you test v0.23.0 to see that this issue is fixed?

**Comment by andrewwebber** [comment] 2017-05-29 08:21
@tatsuhiro-t sure, no problem...

**Comment by andrewwebber** [comment] 2017-06-13 15:11
@tatsuhiro-t I have now tested this it looks like its working - ingress controller with two different ssl certificates

```bash
$kubectl get ingress
NAME              HOSTS                           ADDRESS            PORTS     AGE
guestbook-http    guestbook.brainloopdevops.com   10.10.2.102,1...   80, 443   3m
guestbook2-http   guestbook.brainloop.com         10.10.3.189,1...   80, 443   1m
```

**Comment by tatsuhiro-t** [comment] 2017-06-14 00:52
@andrewwebber Thank you!  Let's close the issue.

**Closed by tatsuhiro-t** 2017-06-14 00:52 UTC
